[package]
name = "aoc_25"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }

itertools = { workspace = true }
once_cell = { workspace = true }
phf = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
